-- Create the feedbacks table
CREATE TABLE feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  product TEXT NOT NULL,
  feedback TEXT NOT NULL,
  sentiment TEXT NOT NULL CHECK (sentiment IN ('Positive', 'Neutral', 'Negative')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) but allow anonymous inserts for the public API
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous inserts" ON feedbacks FOR INSERT TO anon WITH CHECK (true);

-- To view the feedbacks from the dashboard, you could enable read access for authenticated admins:
-- CREATE POLICY "Allow authenticated read access" ON feedbacks FOR SELECT TO authenticated USING (true);
